version: '3.9'
services:
  pythonawsfaggruppe:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: python:3.8
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./source:/source/
      # Map the location of the secrets file,
      # because we NEVER want to check in secrets
      - c:/Users/magnea/.aws:/root/.aws/